version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: webdatxe
        container_name: webdatxe
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: webdatxe
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: webdatxe
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: webdatxe
            MYSQL_USER: root
            MYSQL_PASSWORD: pokemon
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
